In [2]:
import sys
print sys.version
import numpy as np
print np.__version__

2.7.11 |Anaconda 2.4.1 (x86_64)| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)]
1.10.2


In [3]:
npa = np.arange(20)

In [4]:
npa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
[x for x in npa if x % 2 == 0]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [6]:
filter(lambda x: x % 2 == 0, npa)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [7]:
npa % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False], dtype=bool)

In [8]:
npa[npa % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
np2 = np.arange(20000)

In [16]:
#Here we will use the ipython majic function which tells us how long it will take to execute certain things
%timeit [x for x in np2 if x % 2 == 0]

100 loops, best of 3: 7.63 ms per loop


In [17]:
%timeit np2[np2 % 2 == 0]

1000 loops, best of 3: 405 µs per loop


In [18]:
npa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
npa > 10

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True], dtype=bool)

In [20]:
npa[npa > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
%timeit npa[npa > 10]

The slowest run took 9.78 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 2.85 µs per loop


In [22]:
(npa > 15) | (npa < 5)

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True], dtype=bool)

#####  In the above solution Trues are values which satified the condition in the code

In [24]:
# Now we will use boolean selection as dictionary lookup
npa[(npa > 15) | (npa < 5)]

array([ 0,  1,  2,  3,  4, 16, 17, 18, 19])

In [25]:
# Lets look at another example where we will return True for every value in the range of 20
np3 = np.array([True for x in range(20)])

In [26]:
np3

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True], dtype=bool)