In [1]:
import sys
import numpy as np
print sys.version
print np.__version__

2.7.11 |Anaconda 2.4.1 (x86_64)| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)]
1.10.2


In [11]:
npa = np.random.random_integers(0, 50, 20)
#Here we have generated random numbers between 0 and 50 upto 20 values.

In [12]:
npa

array([48, 48, 27, 31,  6, 24, 46, 46, 23,  5, 46, 25, 16, 25, 43,  7,  6,
       18, 26, 25])

In [19]:
map(lambda x: x * 2, npa)

[96,
 96,
 54,
 62,
 12,
 48,
 92,
 92,
 46,
 10,
 92,
 50,
 32,
 50,
 86,
 14,
 12,
 36,
 52,
 50]

In [20]:
[x*2 for x in npa]

[96,
 96,
 54,
 62,
 12,
 48,
 92,
 92,
 46,
 10,
 92,
 50,
 32,
 50,
 86,
 14,
 12,
 36,
 52,
 50]

In [22]:
#In the boolean selection we could simply multiply the array by 2
npa * 2

array([96, 96, 54, 62, 12, 48, 92, 92, 46, 10, 92, 50, 32, 50, 86, 14, 12,
       36, 52, 50])

In [23]:
npa < 5

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False], dtype=bool)

In [24]:
npa ** 3

array([110592, 110592,  19683,  29791,    216,  13824,  97336,  97336,
        12167,    125,  97336,  15625,   4096,  15625,  79507,    343,
          216,   5832,  17576,  15625])

In [25]:
def func(numb):
    if numb < 10:
        return numb ** 3
    else:
        return numb ** 2

In [26]:
new_func(npa)

NameError: name 'new_func' is not defined

In [27]:
?np.vectorize

In [28]:
vnew_func = np.vectorize(func)

In [29]:
type(vnew_func)

numpy.lib.function_base.vectorize

In [30]:
vnew_func(npa)

array([2304, 2304,  729,  961,  216,  576, 2116, 2116,  529,  125, 2116,
        625,  256,  625, 1849,  343,  216,  324,  676,  625])

In [31]:
[func(x) for x in npa]

[2304,
 2304,
 729,
 961,
 216,
 576,
 2116,
 2116,
 529,
 125,
 2116,
 625,
 256,
 625,
 1849,
 343,
 216,
 324,
 676,
 625]

In [32]:
npa2 = np.random.random_integers(0, 100, 20*1000)

In [33]:
#Lets use a tradition list comprehension to loop through npa2 with func and timeit majic function for speed.
%timeit [func(x) for x in npa2]

100 loops, best of 3: 9.66 ms per loop


In [34]:
%timeit vnew_func(npa2)

100 loops, best of 3: 5.76 ms per loop
